### PR TITLE
Fix the fragment instance on vue v1.0.26

### PR DESCRIPTION
**Pull request by timfeid**
Surround the template in a div to fix the 'fragment instance'

### CODE REVIEW

**Comment by timfeid** [comment]
Fixes #10

**Comment by Remo** [comment]
I created the dist files and also checked the final JavaScript file, the div tag was there, but the error didn't disappear. Not sure, maybe I did something wrong, but as long as the DIV tag is there I would assume it works assuming your PR works.

**Comment by timfeid** [comment]
Interesting, for some reason I was able to get this working by just copying vue-html-editor.js to my local. Using `require('vue-html-editor')` fails, but using `require('./vue-html-editor')` works without the div there as well.

**Comment by CMLL** [comment]
So, wrapping the template in a parent element doesn't work? Every piece of documentation points that it should. I tried copying the vue-html-editor file over to the local folder and can confirm that it does solved the component being loaded as a fragment, even when the template only has a textarea.

The thing is, the component only has one textarea element, so that shouldn't trigger a fragment component as that should only arise if you have 2 top level elements, like 

```
template: "<textarea class='form-control' :name='name'></textarea><textarea class='form-control' :name='name'></textarea>"
```

But having only one there is no need to wrap them in a `<div>`. The fragment error must being triggered from some other reason.

**Comment by ada012** [comment]
@Haixing-Hu @timfeid 

Is there any answer? I changed all the template: 
`"<textarea class='form-control' :name='name'></textarea>"`
 to 
`"<div><textarea class='form-control'", :name='name'></textarea></div>"`
Or is it wrong?

**Comment by milosodalovic** [comment]
Same here.
@Haixing-Hu It's very bad when you find something that should be cool and spend all day trying to make it work with no success...

**Comment by timfeid** [comment]
As I mentioned earlier, I was only able to get this working by copying it to my local and requiring it that way.

**Comment by milosodalovic** [comment]
Didn't work for me...

On 10 Oct 2016, at 23:23, Tim Feid <notifications@github.com<mailto:notifications@github.com>> wrote:

As I mentioned earlier, I was only able to get this working by copying it to my local and requiring it that way.

##

**Pull request closed without merging**
